### ISSUE TITLE
i18n: Do no split sentences in multiple parts for translation

### ISSUE THREAD

**Issue by rakekniven** [medismail/salattime#3]
The following code will cause trouble.

https://github.com/medismail/salattime/blob/8d0ea8f676781d4be30ecedac9bb3bcfb41b8766/lib/DAV/Calendar.php#L260

Please use one string and placeholders. Otherwise translators will struggle and some languages cannot be handled.

See how other nextcloud apps do it.

**Comment by medismail** [comment]
Hi, 
OK, I will update all text with multi strings.

**Comment by medismail** [comment]
Fixed in: 7824eed836457d24b46d002aa374ec82d3a0f36f
